# Copyright 2019-2022 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.rabbitmq.include }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  labels:
    fateMoudle: rabbitmq
{{ include "fate.labels" . | indent 4 }}
{{- if .Values.ingress.rabbitmq.annotations }}
  annotations:
{{ toYaml .Values.ingress.rabbitmq.annotations | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  {{- range .Values.ingress.rabbitmq.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
  {{- end }}
{{- if .Values.ingress.rabbitmq.tls }}
  tls:
{{ toYaml .Values.ingress.rabbitmq.tls | indent 4 }}
{{- end }}
---
{{ end }}