# Copyright 2019-2020 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.hdfs.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: namenode-config
  labels:
    fateMoudle: namenode
{{ include "fate.labels" . | indent 4 }}
data:
  core-site.xml: |
    <configuration>
      <property>
        <name>fs.default.name</name>
        <value>hdfs://0.0.0.0:9000</value>
      </property>
    </configuration>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namenode-env
  labels:
    fateMoudle: namenode
{{ include "fate.labels" . | indent 4 }}
data:
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  CORE_CONF_hadoop_http_staticuser_user: "root"
  CORE_CONF_hadoop_proxyuser_hue_hosts: "*"
  CORE_CONF_hadoop_proxyuser_hue_groups: "*"
  CORE_CONF_io_compression_codecs: org.apache.hadoop.io.compress.SnappyCodec
  HDFS_CONF_dfs_webhdfs_enabled: 'true'
  HDFS_CONF_dfs_permissions_enabled: 'false'
  HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check: 'false'
  YARN_CONF_yarn_log___aggregation___enable: 'true'
  YARN_CONF_yarn_log_server_url: "http://historyserver:8188/applicationhistory/logs/"
  YARN_CONF_yarn_resourcemanager_recovery_enabled: 'true'
  YARN_CONF_yarn_resourcemanager_store_class: org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
  YARN_CONF_yarn_resourcemanager_scheduler_class: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___mb: '8192'
  YARN_CONF_yarn_scheduler_capacity_root_default_maximum___allocation___vcores: '4'
  YARN_CONF_yarn_resourcemanager_fs_state___store_uri: /rmstate
  YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled: 'true'
  YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
  YARN_CONF_yarn_resourcemanager_address: resourcemanager:8032
  YARN_CONF_yarn_resourcemanager_scheduler_address: resourcemanager:8030
  YARN_CONF_yarn_resourcemanager_resource__tracker_address: resourcemanager:8031
  YARN_CONF_yarn_timeline___service_enabled: 'true'
  YARN_CONF_yarn_timeline___service_generic___application___history_enabled: 'true'
  YARN_CONF_yarn_timeline___service_hostname: historyserver
  YARN_CONF_mapreduce_map_output_compress: 'true'
  YARN_CONF_mapred_map_output_compress_codec: org.apache.hadoopac.io.compress.SnappyCodec
  YARN_CONF_yarn_nodemanager_resource_memory___mb: '16384'
  YARN_CONF_yarn_nodemanager_resource_cpu___vcores: '8'
  YARN_CONF_yarn_nodemanager_disk___health___checker_max___disk___utilization___per___disk___percentage: '98.5'
  YARN_CONF_yarn_nodemanager_remote___app___log___dir: /app-logs
  YARN_CONF_yarn_nodemanager_aux___services: mapreduce_shuffle
  MAPRED_CONF_mapreduce_framework_name: yarn
  MAPRED_CONF_mapred_child_java_opts: '-Xmx4096m'
  MAPRED_CONF_mapreduce_map_memory_mb: '4096'
  MAPRED_CONF_mapreduce_reduce_memory_mb: '8192'
  MAPRED_CONF_mapreduce_map_java_opts: '-Xmx3072m'
  MAPRED_CONF_mapreduce_reduce_java_opts: '-Xmx6144m'
  MAPRED_CONF_yarn_app_mapreduce_am_env: HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
  MAPRED_CONF_mapreduce_map_env: HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
  MAPRED_CONF_mapreduce_reduce_env: HADOOP_MAPRED_HOME=/opt/hadoop-3.2.1/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
  labels:
    fateMoudle: namenode
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: namenode
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: namenode
{{ include "fate.labels" . | indent 8 }}
    spec:
    {{ if .Values.persistence.enabled }}
      initContainers:
        - name: delete-lost-found
          image: busybox
          command: ["sh", "-c", "rm -rf /hadoop/dfs/name/lost+found"]
          volumeMounts:
            - name: dfs
              mountPath: /hadoop/dfs/name
    {{ end }}
      containers:
        - name: namenode
          image: {{ .Values.image.registry }}/hadoop-namenode:2.0.0-hadoop2.7.4-java8
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: CLUSTER_NAME
            value: fate
          envFrom:
          - configMapRef:
              name: namenode-env 
          ports:
            - containerPort: 9000
            - containerPort: 9870
            - containerPort: 50070
          volumeMounts:
            - mountPath: /etc/hadoop/core-site.xml
              subPath: core-site.xml
              name: namenode-confs
            - name: dfs
              mountPath: /hadoop/dfs/name
      {{- with .Values.modules.hdfs.namenode.nodeSelector }}
      nodeSelector: 
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.hdfs.namenode.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.hdfs.namenode.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
      {{- end }}
      serviceAccountName: {{ template "serviceAccountName" . }}
      restartPolicy: Always
      volumes:
        - name: namenode-confs
          configMap:
            name: namenode-config
        - name: dfs
        {{ if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.modules.hdfs.namenode.existingClaim | default  "namenode-data" }}
        {{ else }}
          emptyDir: {}
        {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    fateMoudle: namenode
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
    - name: "tcp-9000"
      port: 9000
      targetPort: 9000
      protocol: TCP
      {{- if eq .Values.modules.hdfs.namenode.type "NodePort" "LoadBalancer" }}
      nodePort: {{ .Values.modules.hdfs.namenode.nodePort }}
      {{- end }}
    - name: "tcp-9870"
      port: 9870
      targetPort: 9870
      protocol: TCP
    - name: "tcp-50070"
      port: 50070
      targetPort: 50070
      protocol: TCP
  type: {{ .Values.modules.hdfs.namenode.type }}
  selector:
    fateMoudle: namenode
{{ include "fate.matchLabels" . | indent 4 }}
---
{{ if and .Values.persistence.enabled (not .Values.modules.hdfs.namenode.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: namenode-data
  labels:
    fateMoudle: namenode
{{ include "fate.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.modules.hdfs.namenode.accessMode }}
  resources:
    requests:
      storage: {{ .Values.modules.hdfs.namenode.size }}
  {{ if .Values.modules.hdfs.namenode.storageClass }}
    {{ if eq "-" .Values.modules.hdfs.namenode.storageClass }}
  storageClassName: ""
    {{ else }}
  storageClassName: {{ .Values.modules.hdfs.namenode.storageClass }}
    {{ end }}
  {{ end }}
{{ end }}
{{ end }}
