{{- if .Values.podSecurityPolicy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    fateMoudle: serviceAccount
{{ include "fate.labels" . | indent 4 }}
  name: {{ .Values.partyName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.partyName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.partyName }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
