# Copyright 2019-2020 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.spark.include }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    fateMoudle: spark-master
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.modules.spark.master.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: spark-master
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: spark-master
{{ include "fate.labels" . | indent 8 }}
    spec:
      containers:
        - name: spark-master
          image: {{ if .Values.modules.spark.master.Image }}{{ .Values.modules.spark.master.Image }}{{ else }}{{ .Values.image.registry }}/spark-master{{ end }}:{{ default .Values.image.tag .Values.modules.spark.master.ImageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PYSPARK_PYTHON
            value: /data/projects/python/venv/bin/python
          - name: PYSPARK_DRIVER_PYTHON
            value: /data/projects/python/venv/bin/python
          resources:
            requests:
              cpu: "{{ .Values.modules.spark.worker.cpu }}"
              memory: "{{ .Values.modules.spark.worker.memory }}"
          ports:
            - containerPort: 8080
            - containerPort: 7077
            - containerPort: 6066
      {{- with .Values.modules.spark.master.nodeSelector }}
      nodeSelector: 
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    fateMoudle: spark-master
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: master-rest
    protocol: TCP
    port: 6066
    targetPort: 6066
  type: {{ .Values.modules.spark.master.type }}
  clusterIP: None
  selector:
    fateMoudle: spark-master
{{ include "fate.matchLabels" . | indent 4 }}
---
{{ end }}
