# Copyright 2019-2020 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.spark.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-worker-config
  labels:
    fateMoudle: spark-worker
{{ include "fate.labels" . | indent 4 }}
data:
  service_conf.yaml: |
    work_mode: 1
    database:
      name: fate_flow
      user: fate
      passwd: fate
      host: 127.0.0.1
      port: 3306
      max_connections: 100
      stale_timeout: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    fateMoudle: spark-worker
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.modules.spark.worker.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: spark-worker
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: spark-worker
{{ include "fate.labels" . | indent 8 }}
    spec:
      containers:
        - name: spark-worker
          image: {{ if .Values.modules.spark.worker.Image }}{{ .Values.modules.spark.worker.Image }}{{ else }}{{ .Values.image.registry }}/spark-worker{{ end }}:{{ default .Values.image.tag .Values.modules.spark.worker.ImageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.modules.spark.worker.resources }}
          resources:
          {{- range $key, $val := .Values.modules.spark.worker.resources }}
            {{ $key }}:
{{ toYaml $val | indent 14 }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /data/projects/fate/conf/
              name: spark-worker-confs
          ports:
            - containerPort: 8081
      {{- with .Values.modules.spark.worker.nodeSelector }}
      nodeSelector: 
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.spark.worker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.spark.worker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
      {{- end }}
      serviceAccountName: {{ template "serviceAccountName" . }}
      restartPolicy: Always
      volumes:
        - name: spark-worker-confs
          configMap:
            name: spark-worker-config
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-1
  labels:
    fateMoudle: spark-worker
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
    - name: "tcp-spark"
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: {{ .Values.modules.spark.worker.type }}
  clusterIP: None
  selector:
    fateMoudle: spark-worker
{{ include "fate.matchLabels" . | indent 4 }}
---
{{ end }}
