########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################
#

#nfspath: /data/fate-data
#nfsserver: 192.168.0.2

image:
  registry: federatedai
  isThridParty:
  tag: 1.2.0-release
  pullPolicy: IfNotPresent
partyId: 10000
host:
  fateboard: 10000.fateboard.fedai.org
nodePort: 30010

exchange:
  partyIp: 192.168.1.1
  partyPort: 30000

partyList:
#  - partyId:
#    partyIp:
#    partyPort:

mysql:
  mysql_root_password: fate_dev
  mysql_database: fate
  mysql_user: fate
  mysql_password: fate_dev
redis:
  requirepass: fate_dev
eggList:
  - egg: egg
    nodeLabel: fedai.org
    value: 
nodeSelector:
  fateboard:
    nodeLabel: fedai.org
    value: 
  federation:
    nodeLabel: fedai.org
    value: 
  metaService:
    nodeLabel: fedai.org
    value: 
  mysql:
    nodeLabel: fedai.org
    value: 
  proxy:
    nodeLabel: fedai.org
    value: 
  python:
    nodeLabel: fedai.org
    value: 
  redis:
    nodeLabel: fedai.org
    value: 
  roll:
    nodeLabel: fedai.org
    value: 
  servingServer:
    nodeLabel: fedai.org
    value: 

modules:
  proxy: 
    include: true
    ip: proxy
    type: NodePort
  egg: 
    include: true
    ip: egg
    type: ClusterIP
  fateboard: 
    include: true
    ip: fateboard
    type: ClusterIP
  fateflow: 
    include: true
    ip: fateflow
    type: ClusterIP
  federation: 
    include: true
    ip: federation
    type: ClusterIP
  metaService: 
    include: true
    ip: meta-service
    type: ClusterIP
  mysql: 
    include: true
    ip: mysql
    type: ClusterIP
  redis: 
    include: true
    ip: redis
    type: ClusterIP
  roll: 
    include: true
    ip: roll
    type: ClusterIP
  python: 
    include: true
    ip: python
    type: ClusterIP
