# Copyright 2019-2022 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.pulsar.include }}
{{- if and .Values.persistence.enabled (not .Values.modules.pulsar.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pulsar-data
  labels:
    fateMoudle: pulsar
{{ include "fate.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.modules.pulsar.accessMode }}
  resources:
    requests:
      storage: {{ .Values.modules.pulsar.size }}
  {{ if .Values.modules.pulsar.storageClass }}
    {{ if eq "-" .Values.modules.pulsar.storageClass }}
  storageClassName: ""
    {{ else }}
  storageClassName: {{ .Values.modules.pulsar.storageClass }}
    {{ end }}
  {{ end }}
{{- end }}
{{ end }}