# Copyright 2019-2022 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.pulsar.include }}
apiVersion: v1
kind: Service
metadata:
  name: pulsar
  labels:
    fateMoudle: pulsar
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
  - name: "http-port"
    port: 6650
    targetPort: 6650
    {{- if eq .Values.modules.pulsar.type "NodePort" "LoadBalancer" }}
    nodePort: {{ .Values.modules.pulsar.httpNodePort }}
    {{- end }}
    protocol: TCP
  - name: "https-port"
    port: 6651
    targetPort: 6651
    {{- if eq .Values.modules.pulsar.type "NodePort" "LoadBalancer" }}
    nodePort: {{ .Values.modules.pulsar.httpsNodePort }}
    {{- end }}
    protocol: TCP
  - name: "mng-port"
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: "mngs-port"
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: {{ .Values.modules.pulsar.type }}
  
  {{- if .Values.modules.pulsar.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.modules.pulsar.loadBalancerIP }}"
  {{- end }}
  
  selector:
    fateMoudle: pulsar
{{ include "fate.matchLabels" . | indent 4 }}

---

{{- if .Values.modules.pulsar.publicLB.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pulsar-public-tls
  labels:
    fateMoudle: pulsar
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
  - name: "tls-port"
    port: 6651
    targetPort: 6651
    protocol: TCP
  type: LoadBalancer
  selector:
    fateMoudle: pulsar
{{ include "fate.matchLabels" . | indent 4 }}
{{- end }}

{{ end }}