# Copyright 2019-2020 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


{{- if .Values.modules.nodemanager.include }}
{{- $root := . -}}
{{- range $nodemanager := .Values.modules.nodemanager.list }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $nodemanager.name }}-config
  labels:
    fateMoudle: {{ $nodemanager.name }}
{{ include "fate.labels" $root | indent 4 }}
data:
  eggroll.properties: |
    [eggroll]
    eggroll.resourcemanager.clustermanager.jdbc.driver.class.name=com.mysql.cj.jdbc.Driver
    eggroll.resourcemanager.clustermanager.jdbc.url=jdbc:mysql://{{ $root.Values.modules.mysql.ip }}:{{ $root.Values.modules.mysql.port }}/{{ $root.Values.modules.mysql.mysql_database }}?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    eggroll.resourcemanager.clustermanager.jdbc.username={{ $root.Values.modules.mysql.mysql_user }}
    eggroll.resourcemanager.clustermanager.jdbc.password={{ $root.Values.modules.mysql.mysql_password }}
    
    eggroll.data.dir=data/
    eggroll.logs.dir=logs/
    eggroll.resourcemanager.clustermanager.host=clustermanager
    eggroll.resourcemanager.clustermanager.port=4670
    eggroll.resourcemanager.nodemanager.port=4671
    eggroll.resourcemanager.process.tag={{ $root.Values.partyId }}
    
    eggroll.bootstrap.root.script=bin/eggroll_boot.sh
    
    eggroll.resourcemanager.bootstrap.egg_pair.exepath=bin/roll_pair/egg_pair_bootstrap.sh
    eggroll.resourcemanager.bootstrap.egg_pair.venv=/data/projects/python/venv
    eggroll.resourcemanager.bootstrap.egg_pair.pythonpath=/data/projects/fate/python:/data/projects/fate/eggroll/python
    eggroll.resourcemanager.bootstrap.egg_pair.filepath=python/eggroll/roll_pair/egg_pair.py
    
    
    eggroll.resourcemanager.bootstrap.roll_pair_master.exepath=bin/roll_pair/roll_pair_master_bootstrap.sh
    eggroll.resourcemanager.bootstrap.roll_pair_master.javahome=/usr/lib/jvm/java-1.8.0-openjdk
    eggroll.resourcemanager.bootstrap.roll_pair_master.classpath=conf/:lib/*
    eggroll.resourcemanager.bootstrap.roll_pair_master.mainclass=com.webank.eggroll.rollpair.RollPairMasterBootstrap
    eggroll.resourcemanager.bootstrap.roll_pair_master.jvm.options=
    
    # roll site
    eggroll.rollsite.coordinator={{ $root.Values.partyName }}
    eggroll.rollsite.host=rollsite
    eggroll.rollsite.port=9370
    eggroll.rollsite.party.id={{ $root.Values.partyId }}
    eggroll.rollsite.route.table.path=conf/route_table.json
    
    
    eggroll.session.processors.per.node={{ $nodemanager.sessionProcessorsPerNode }}
    eggroll.session.start.timeout.ms=180000
    eggroll.rollsite.adapter.sendbuf.size=1048576
    eggroll.rollpair.transferpair.sendbuf.size=4150000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $nodemanager.name }}
  labels:
    fateMoudle: {{ $nodemanager.name }}
{{ include "fate.labels" $root | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: {{ $nodemanager.name }}
{{ include "fate.matchLabels" $root | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: {{ $nodemanager.name }}
{{ include "fate.labels" $root | indent 8 }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ $nodemanager.name }}"
      containers:
        - image: {{ $root.Values.image.registry }}/eggroll:{{ $root.Values.image.tag }}
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          name: {{ $nodemanager.name }}
          command:
          - bash
          - -c
          - "java -Dlog4j.configurationFile=$${EGGROLL_HOME}/conf/log4j2.properties -cp $${EGGROLL_HOME}/lib/*: com.webank.eggroll.core.Bootstrap --bootstraps com.webank.eggroll.core.resourcemanager.NodeManagerBootstrap -c $${EGGROLL_HOME}/conf/eggroll.properties -p 4671 -s 'EGGROLL_DEAMON'"
          ports:
            - containerPort: 4671
          volumeMounts:
            - mountPath: /data/projects/fate/eggroll/conf/eggroll.properties
              name: nodemanager-confs
              subPath: eggroll.properties
            - mountPath: /data/projects/fate/python/arch/conf/server_conf.json
              name: python-confs
              subPath: server_conf.json
            - name: data-dir
              mountPath: /data/projects/fate/eggroll/data
              subPath: {{ $nodemanager.subPath }}
      {{- with $nodemanager.nodeSelector }}
      nodeSelector: 
      {{- range $k, $v := . }}
        {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: nodemanager-confs
          configMap:
            name: {{ $nodemanager.name }}-config
        - name: python-confs
          configMap:
            name: python-config
        {{- if not $root.Values.persistence.enabled }}
        - name: data-dir
          emptyDir: {}
        {{- else }}
        - name: data-dir
          persistentVolumeClaim:
            claimName: {{ $nodemanager.existingClaim | default (printf "%s-data" $nodemanager.name) }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    fateMoudle: {{ $nodemanager.name }}
{{ include "fate.labels" $root | indent 4 }}
  name: {{ $nodemanager.name }}
spec:
  ports:
    - name: "4671"
      port: 4671
      targetPort: 4671
      protocol: TCP
  clusterIP: None
  selector:
    fateMoudle: {{ $nodemanager.name }}
{{ include "fate.matchLabels" $root | indent 4 }}
---
{{- if and $root.Values.persistence.enabled (not $nodemanager.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $nodemanager.name }}-data
  labels:
    fateMoudle: {{ $nodemanager.name }}
{{ include "fate.labels" $root | indent 4 }}
spec:
  accessModes: 
    - {{ $nodemanager.accessMode }}
  resources:
    requests:
      storage: {{ $nodemanager.size }}
  {{- if $nodemanager.storageClass }}
    {{- if eq "-" $nodemanager.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $nodemanager.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}

---
{{- end }}
{{- end }}