# Copyright 2019-2020 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.python.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: python-config
  labels:
    fateMoudle: python
{{ include "fate.labels" . | indent 4 }}
data:
  server_conf.json: |
    {
        "servers": {
            "proxy": {
                "host": "{{ .Values.modules.rollsite.ip }}", 
                "port": 9370
            }, 
            "fateboard": {
                "host": "{{ .Values.modules.python.fateboardIp }}", 
                "port": 8080
            }, 
            {{- if .Values.modules.serving }}
            "servings": [
                "{{ .Values.modules.serving.ip }}:{{ .Values.modules.serving.port }}"
            ],
            {{- end }}
            "fateflow": {
                "host": "{{ .Values.modules.python.fateflowIp }}", 
                "grpc.port": 9360,
                "http.port": 9380
            }
        }
    }
  settings.py: | 
    # -*- coding: utf-8 -*-
    import os
    
    from arch.api import Backend
    from arch.api.utils import file_utils, log_utils
    from fate_flow.entity.runtime_config import RuntimeConfig
    from arch.api.utils.conf_utils import get_base_config
    import __main__
    

    WORK_MODE = get_base_config('work_mode', 0)
    BACKEND = Backend.EGGROLL
    USE_LOCAL_DATABASE = True
    
    # upload data
    USE_LOCAL_DATA = True
    
    # Local authentication switch
    USE_AUTHENTICATION = False
    PRIVILEGE_COMMAND_WHITELIST = []
    
    # Node check switch
    CHECK_NODES_IDENTITY = False

    # Registry
    SERVICES_SUPPORT_REGISTRY = ["servings", "fateflow"]
    FATE_SERVICES_REGISTERED_PATH = {
        "fateflow": "/FATE-SERVICES/flow/online/transfer/providers",
        "servings": "/FATE-SERVICES/serving/online/publishLoad/providers",
    }

    # FILE CONF
    SERVER_CONF_PATH = 'arch/conf/server_conf.json'


    # job maximum number  of the initiator
    MAX_CONCURRENT_JOB_RUN = 5

    # Limit the number of jobs on the host side
    LIMIT_ROLE = 'host'
    MAX_CONCURRENT_JOB_RUN_HOST = 5
    RE_ENTRY_QUEUE_TIME = 2*60
    RE_ENTRY_QUEUE_MAX = 60


    _ONE_DAY_IN_SECONDS = 60 * 60 * 24
    DEFAULT_GRPC_OVERALL_TIMEOUT = 60 * 1000 * 60  # ms
    JOB_DEFAULT_TIMEOUT = 7 * 24 * 60 * 60
    DATABASE = get_base_config("database", {})
    MODEL_STORE_ADDRESS = get_base_config("model_store_address", {})

    '''
    Constants
    '''
    API_VERSION = "v1"
    ROLE = 'fateflow'
    SERVERS = 'servers'
    MAIN_MODULE = os.path.relpath(__main__.__file__)
    SERVER_MODULE = 'fate_flow_server.py'
    TASK_EXECUTOR_MODULE = 'driver/task_executor.py'
    TEMP_DIRECTORY = os.path.join(file_utils.get_project_base_directory(), "fate_flow", "temp")
    HEADERS = {
        'Content-Type': 'application/json',
        'Connection': 'close'
    }
    DETECT_TABLE = ("fate_flow_detect_table_namespace", "fate_flow_detect_table_name", 16)

    # endpoint
    FATE_FLOW_MODEL_TRANSFER_ENDPOINT = '/v1/model/transfer'
    FATE_MANAGER_GET_NODE_INFO_ENDPOINT = '/fate-manager/api/site/secretinfo'
    FATE_MANAGER_NODE_CHECK_ENDPOINT = '/fate-manager/api/site/checksite'
    FATE_BOARD_DASHBOARD_ENDPOINT = '/index.html#/dashboard?job_id={}&role={}&party_id={}'

    # logger
    log_utils.LoggerFactory.LEVEL = 10
    # {CRITICAL: 50, FATAL:50, ERROR:40, WARNING:30, WARN:30, INFO:20, DEBUG:10, NOTSET:0}
    log_utils.LoggerFactory.set_directory(os.path.join(file_utils.get_project_base_directory(), 'logs', 'fate_flow'))
    stat_logger = log_utils.getLogger("fate_flow_stat")
    detect_logger = log_utils.getLogger("fate_flow_detect")
    access_logger = log_utils.getLogger("fate_flow_access")

    """
    Services
    """
    IP = get_base_config("fate_flow", {}).get("host", "0.0.0.0")
    HTTP_PORT = get_base_config("fate_flow", {}).get("http_port")
    GRPC_PORT = get_base_config("fate_flow", {}).get("grpc_port")

    # standalone job will be send to the standalone job server when FATE-Flow work on cluster deploy mode,
    # but not the port for FATE-Flow on standalone deploy mode.
    CLUSTER_STANDALONE_JOB_SERVER_PORT = 9381

    # switch
    SAVE_AS_TASK_INPUT_DATA_SWITCH = True
    SAVE_AS_TASK_INPUT_DATA_IN_MEMORY = True
    ALIGN_TASK_INPUT_DATA_PARTITION_SWITCH = True

    # init
    RuntimeConfig.init_config(WORK_MODE=WORK_MODE)
    RuntimeConfig.init_config(HTTP_PORT=HTTP_PORT)
    RuntimeConfig.init_config(BACKEND=BACKEND)

  base_conf.yaml: |
    work_mode: 1
    fate_flow:
      host: 0.0.0.0
      http_port: 9380
      grpc_port: 9360
    database:
      name: '{{ .Values.modules.mysql.database }}'
      user: '{{ .Values.modules.mysql.user }}'
      passwd: '{{ .Values.modules.mysql.password }}'
      host: '{{ .Values.modules.mysql.ip }}'
      port: {{ .Values.modules.mysql.port }}
      max_connections: 100
      stale_timeout: 30
    redis:
      host: 127.0.0.1
      port: 6379
      password: WEBANK_2014_fate_dev
      max_connections: 500
      db: 0
    default_model_store_address:
      storage: redis
      host: 127.0.0.1
      port: 6379
      password: fate_dev
      db: 0
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fateboard-config
  labels:
    fateMoudle: fateboard
{{ include "fate.labels" . | indent 4 }}
data:
  application.properties: |
    server.port=8080
    fateflow.url=http://{{ .Values.modules.python.fateflowIp }}:9380
    spring.datasource.driver-Class-Name=com.mysql.cj.jdbc.Driver
    spring.http.encoding.charset=UTF-8
    spring.http.encoding.enabled=true
    server.tomcat.uri-encoding=UTF-8
    fateboard.datasource.jdbc-url=jdbc:mysql://{{ .Values.modules.mysql.ip }}:{{ .Values.modules.mysql.port }}/{{ .Values.modules.mysql.database }}?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    fateboard.datasource.username={{ .Values.modules.mysql.user }}
    fateboard.datasource.password={{ .Values.modules.mysql.password }}
    server.tomcat.max-threads=1000
    server.tomcat.max-connections=20000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    fateMoudle: python
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: python
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: python
{{ include "fate.labels" . | indent 8 }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "fateflow"
      initContainers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.modules.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.modules.mysql.user }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.modules.mysql.password }}
        - name: MYSQL_HOST
          value: {{ .Values.modules.mysql.ip }}
        - name: MYSQL_PORT
          value: {{ .Values.modules.mysql.port  | quote }}
        command:
        - /bin/bash
        - -c
        - |
          set -x
          function checkMySQL(){
            checkMySQLCount=0
            while true ; do
              checkMySQLCount=$[checkMySQLCount+1]
              echo "Waiting for mysql started. check count: $checkMySQLCount"
              sleep 2

              state=`mysqladmin ping -h ${MYSQL_HOST} --port=${MYSQL_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD}| awk '{print $3}'`
              if [ "$state" == "alive" ]; then
                echo "mysql server has been already started."
              break
              fi
           done
          }
          echo "Waiting for mysql started..."
          checkMySQL
      containers:
        - image: {{ .Values.image.registry }}/python:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: python
          ports:
            - containerPort: 9360
            - containerPort: 9380
            - containerPort: 8484
          volumeMounts:
            - mountPath: /data/projects/fate/python/eggroll/conf/server_conf.json
              name: python-confs
              subPath: server_conf.json
            - mountPath: /data/projects/fate/eggroll/conf/eggroll.properties
              name: eggroll-confs
              subPath: eggroll.properties
            - mountPath: /data/projects/fate/python/arch/conf/server_conf.json
              name: python-confs
              subPath: server_conf.json
            - mountPath: /data/projects/fate/python/fate_flow/settings.py
              subPath: settings.py
              name: python-confs
            - mountPath: /data/projects/fate/python/arch/conf/base_conf.yaml
              subPath: base_conf.yaml
              name: python-confs
            - name: logs
              mountPath: /data/projects/fate/python/logs
            - name: download-dir
              mountPath: /data/projects/fate/python/download_dir
        {{- if .Values.modules.client.include }}
        - image: {{ .Values.image.registry }}/client:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: client
          env:
            - name: partyId
              value: {{ .Values.partyId | quote  }}
          ports:
            - containerPort: 20000
          volumeMounts:
            - mountPath: /data/projects/fate/python/arch/conf/server_conf.json
              name: python-confs
              subPath: server_conf.json
            - mountPath: /data/projects/fate/python/fate_flow/settings.py
              subPath: settings.py
              name: python-confs
            - name: logs
              mountPath: /data/projects/fate/client/logs
            - name: download-dir
              mountPath: /data/projects/fate/python/download_dir
        {{- end }}
        - image: {{ .Values.image.registry }}/fateboard:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: fateboard
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data/projects/fate/fateboard/conf/application.properties
              name: fateboard-confs
              subPath: application.properties
            - name: logs
              mountPath: /data/projects/fate/python/logs
      {{- with .Values.modules.python.nodeSelector }}
      nodeSelector:
      {{- range $k, $v := . }}
        {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: python-confs
          configMap:
            name: python-config
        - name: eggroll-confs
          configMap:
            name: eggroll-config
        - name: fateboard-confs
          configMap:
            name: fateboard-config
        - name: logs
          emptyDir: {}
        - name: download-dir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fateflow
  labels:
    fateMoudle: python
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
    - name: "9360"
      port: 9360
      targetPort: 9360
      protocol: TCP
    - name: "9380"
      port: 9380
      {{- with .Values.modules.python.fateflowNodePort }}
      nodePort: {{ . }}
      {{- end }}
      targetPort: 9380
      protocol: TCP
  type: {{ .Values.modules.python.fateflowType }}
  selector:
    fateMoudle: python
{{ include "fate.matchLabels" . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: fateboard
  labels:
    fateMoudle: python
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: {{ .Values.modules.python.fateboardType }}
  selector:
    fateMoudle: python
{{ include "fate.matchLabels" . | indent 4 }}
---
{{- if .Values.modules.client.include }}
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    fateMoudle: python
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
    - name: "20000"
      port: 20000
      targetPort: 20000
      protocol: TCP
  type: {{ .Values.modules.client.type }}
  selector:
    fateMoudle: python
{{ include "fate.matchLabels" . | indent 4 }}
---
{{- end }}
{{ end }}
