partyId: 1
partyName: fate-exchange

image:
  registry: federatedai
  isThridParty: false
  tag: 1.6.0-release
  pullPolicy: IfNotPresent
  imagePullSecrets: 
#  - name: 

exchange:
  partyIp: 192.168.0.1
  partyPort: 30000

partyList:
  - partyId: 10000
    partyIp: 192.168.0.1
    partyPort: 30101

modules:
  rollsite: 
    include: false
    type: NodePort
    nodePort: 30091
    partyList:
      - partyId: 10000
        partyIp: 192.168.0.1
        partyPort: 30101
  trafficServer:
    include: true
    type: ClusterIP
    nodePort: 30097
    route_table: 
      sni:
      - fqdn: 10000.fate.org
        tunnelRoute: 192.168.0.2:6651
      - fqdn: 9999.fate.org
        tunnelRoute: 192.168.0.3:6651
