name: fate-exchange
namespace: fate-exchange
chartName: fate-exchange
chartVersion: v1.6.0
partyId: 1
registry: ""
imageTag: ""
pullPolicy: 
persistence: false
istio:
  enabled: false
modules:
  - trafficServer

rollsite: 
  type: NodePort
  nodePort: 30091
  exchange:
    ip: 192.168.0.1
    port: 30000
  partyList:
  - partyId: 10000
    partyIp: 192.168.0.1
    partyPort: 30101
  nodeSelector:
  tolerations:
  affinity:

trafficServer:
  type: ClusterIP
  nodePort: 30097
  route_table: 
    sni:
    - fqdn: 10000.fate.org
      tunnelRoute: 192.168.0.2:6651
    - fqdn: 9999.fate.org
      tunnelRoute: 192.168.0.3:6651
  nodeSelector:
  tolerations:
  affinity:
