partyId: {{ .partyId }}
partyName: {{ .name }}

image:
  registry: {{ .registry | default "federatedai" }}
  isThridParty: {{ empty .registry | ternary  "false" "true" }}
  tag: {{ .imageTag | default "1.8.0-release" }}
  pullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
  {{- with .imagePullSecrets }}
  imagePullSecrets:
{{ toYaml . | indent 2 }}
  {{- end }}

exchange:
{{- with .rollsite }}
{{- with .exchange }}
  partyIp: {{ .ip }}
  partyPort: {{ .port }}
{{- end }}
{{- end }}

{{- with .podSecurityPolicy }}
podSecurityPolicy:
  enabled: {{ .enabled | default false }}
{{- end }}

partyList:
{{- with .rollsite }}
{{- range .partyList }}
  - partyId: {{ .partyId }}
    partyIp: {{ .partyIp }}
    partyPort: {{ .partyPort }}
{{- end }}
{{- end }}

modules:
  rollsite: 
    include: {{ has "rollsite" .modules }}
    {{- with .rollsite }}
    {{- with .nodeSelector }}
    nodeSelector: 
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .tolerations }}
    tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .affinity }}
    affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
    type: {{ .type }}
    nodePort: {{ .nodePort }}
    partyList:
    {{- range .partyList }}
      - partyId: {{ .partyId }}
        partyIp: {{ .partyIp }}
        partyPort: {{ .partyPort }}
    {{- end }}
    {{- end }}
  nginx:
    include: {{ has "nginx" .modules }}
    {{- with .nginx }}
    {{- with .nodeSelector }}
    nodeSelector: 
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .tolerations }}
    tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .affinity }}
    affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
    type: {{ .type }}
    replicas: {{ .replicas }}
    httpNodePort:  {{ .httpNodePort }}
    grpcNodePort:  {{ .grpcNodePort }}
    route_table: 
      {{- range $key, $val := .route_table }}
      {{ $key }}: 
{{ toYaml $val | indent 8 }}
      {{- end }}
    {{- end }}
  trafficServer:
    include: {{ has "trafficServer" .modules }}
    {{- with .trafficServer }}
    {{- with .nodeSelector }}
    nodeSelector: 
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .tolerations }}
    tolerations:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .affinity }}
    affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
    type: {{ .type }}
    replicas: {{ .replicas }}
    nodePort: {{ .nodePort }}
    route_table: 
      sni:
    {{- range .route_table.sni }}
      - fqdn: {{ .fqdn }}
        tunnelRoute: {{ .tunnelRoute }}
    {{- end }}
    {{- end }}
