name: fate-exchange
namespace: fate-exchange
chartName: fate-exchange
chartVersion: v1.8.0
partyId: 1
registry: ""
imageTag: "1.8.0-release"
pullPolicy: 
imagePullSecrets: 
- name: myregistrykey
persistence: false
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
modules:
  - rollsite
  - trafficServer
  - nginx

rollsite: 
  type: NodePort
  nodePort: 30001
  loadBalancerIP: 192.168.0.1
  partyList:
  - partyId: 10000
    partyIp: 192.168.10.1
    partyPort: 30101
  nodeSelector:
  tolerations:
  affinity:

trafficServer:
  replicas: 3
  nodeSelector:
  tolerations:
  affinity:
  type: NodePort
  nodePort: 30007
  loadBalancerIP: 192.168.0.1
  route_table: 
    sni:
    - fqdn: 10000.fate.org
      tunnelRoute: 192.168.0.2:30109
    - fqdn: 9999.fate.org
      tunnelRoute: 192.168.0.3:30099

nginx:
  replicas: 3
  nodeSelector:
  tolerations:
  affinity:
  type: NodePort
  httpNodePort: 30003
  grpcNodePort: 30008
  loadBalancerIP: 192.168.0.1
  route_table: 
    9999: 
      proxy: 
        - host: 192.168.9.1 
          http_port: 30093
          grpc_port: 30098 
      fateflow: 
        - host: 192.168.9.1
          http_port: 30097
          grpc_port: 30092
    10000: 
      proxy: 
        - host: 192.168.10.1 
          http_port: 30103
          grpc_port: 30108 
      fateflow: 
        - host: 192.168.10.1
          http_port: 30107
          grpc_port: 30102
