# Copyright 2019-2022 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.osx.include }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osx
  labels:
    fateMoudle: osx
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: osx
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: osx
{{ include "fate.labels" . | indent 8 }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "osx"
      containers:
        - name: osx
          env:
          - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
            value: python
          image: {{ .Values.image.registry }}{{ .Values.modules.osx.image }}:{{ .Values.modules.osx.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.modules.osx.resources}}
          resources:
          {{- range $key, $val := .Values.modules.osx.resources }}
            {{ $key }}:
{{ toYaml $val | indent 14 }}
          {{- end }}
          {{- end }}
          command:
          - sh
          - -c
          - |
            set -x
            {{- if .Values.modules.osx.enableTLS }}
            cat /data/projects/fate/eggroll/conf/cert_configs >> /data/projects/fate/eggroll/conf/eggroll.properties
            {{- end}}
            java -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -verbose:gc -Xloggc:/dev/shm/rmq_srv_gc_%p_%t.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/oom/heapdump.hprof  -server -Xms4g -Xmx4g -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=15g -XX:-UseLargePages -XX:-UseBiasedLocking  -cp conf/broker/:lib/*:extension/*:/data/projects/fate/osx/lib/osx-broker-1.0.0.jar org.fedai.osx.broker.Bootstrap -c /data/projects/fate/osx/conf
          ports:
            - containerPort: 9370
          livenessProbe:
            tcpSocket:
              port: 9370
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9370
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 9370
            failureThreshold: 12
            periodSeconds: 10
          volumeMounts:
            - mountPath: /data/projects/fate/osx/conf/broker/
              name: osx-confs
            {{- if .Values.modules.osx.enableTLS }}
            - mountPath: /data/projects/fate/eggroll/conf/cert_configs
              name: eggroll-confs
              subPath: cert_configs
            - mountPath: /data/projects/fate/eggroll/conf/cert/
              name: eggroll-certs
            {{- end }}
      {{- with .Values.modules.osx.nodeSelector }}
      nodeSelector: 
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.osx.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.osx.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
      {{- end }}
      serviceAccountName: {{ template "serviceAccountName" . }}
      restartPolicy: Always
      volumes:
        - name: osx-confs
          configMap:
            name: osx-config
        - name: eggroll-confs
          configMap:
            name: eggroll-config
        {{- if .Values.modules.osx.enableTLS }}
        - name: eggroll-certs
          secret:
            secretName: eggroll-certs
        {{- end}}
{{ end }}