{{- if .Values.podSecurityPolicy.enabled  -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    fateMoudle: role
{{ include "fate.labels" . | indent 4 }}
  name: {{ .Values.partyName }}
rules:
  - apiGroups:      ['policy']
    resources:      ['podsecuritypolicies']
    verbs:          ['use']
    resourceNames:  [{{ .Values.partyName }}]
{{- end -}}
