# Copyright 2019-2020 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.modules.rollsite.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: rollsite-config
  labels:
    fateMoudle: rollsite
{{ include "fate.labels" . | indent 4 }}
data:
  eggroll.properties: |
    # rollsite
    eggroll.rollsite.coordinator={{ .Values.partyName }}
    eggroll.rollsite.host=rollsite
    eggroll.rollsite.port=9370
    eggroll.rollsite.party.id={{ .Values.partyId }}
    eggroll.rollsite.route.table.path=conf/route_table/route_table.json
    eggroll.rollsite.route.table.key=
    eggroll.rollsite.route.table.whitelist=127.0.0.1
    eggroll.rollsite.jvm.options=-XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:logs/eggroll/rollsite.gc.log
    
    eggroll.rollsite.push.max.retry=3
    eggroll.rollsite.push.long.retry=2
    eggroll.rollsite.push.batches.per.stream=10
    eggroll.rollsite.adapter.sendbuf.size=100000

  route_table.json: |
    {
        "route_table": {
            "default": {
                "default": [
                    {
                      {{- with .Values.exchange }}
                        "ip": "{{ .partyIp }}",
                        "port": {{ .partyPort }}
                      {{- else }}
                        "ip": "rollsite",
                        "port": 9370
                      {{- end }}
                    }
                ]
            },
            {{- range .Values.partyList }}
            "{{ .partyId }}": {
                "default": [
                    {
                        "ip": "{{ .partyIp }}",
                        "port": {{ .partyPort }}
                    }
                ]
            },
            {{- end }}
            "{{ .Values.partyId }}": {
                "fateflow": [
                    {
                        "ip": "fateflow",
                        "port": 9360
                    }
                ],
                "default": [
                    {
                        "ip": "rollsite",
                        "port": 9370
                    }
                ]
            }
        },
        "permission": {
            "default_allow": true
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollsite
  labels:
    fateMoudle: rollsite
{{ include "fate.labels" . | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: rollsite
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        fateMoudle: rollsite
{{ include "fate.labels" . | indent 8 }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "rollsite"
      containers:
        - name: rollsite
          env:
          - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
            value: python
          image: {{ .Values.image.registry }}/eggroll:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - bash
          - -c
          - |
            set -x
            mkdir -p /data/projects/fate/eggroll/logs/eggroll/
            touch /data/projects/fate/eggroll/logs/eggroll/eggroll-audit.log
            ln -sf /dev/stdout /data/projects/fate/eggroll/logs/eggroll/eggroll-audit.log
            touch /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.log
            ln -sf /dev/stdout /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.log
            touch /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.err.log 
            ln -sf /dev/stderr /data/projects/fate/eggroll/logs/eggroll/eggroll.jvm.err.log
            java -Dlog4j.configurationFile=$${EGGROLL_HOME}/conf/log4j2.properties -cp $${EGGROLL_HOME}/lib/*:$${EGGROLL_HOME}/conf/ com.webank.eggroll.rollsite.EggSiteBootstrap -c $${EGGROLL_HOME}/conf/eggroll.properties
          ports:
            - containerPort: 9370
          volumeMounts:
            - mountPath: /data/projects/fate/eggroll/conf/route_table/
              name: rollsite-confs
            - mountPath: /data/projects/fate/eggroll/conf/eggroll.properties
              name: rollsite-confs
              subPath: eggroll.properties
      {{- with .Values.modules.rollsite.nodeSelector }}
      nodeSelector: 
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.rollsite.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.rollsite.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
      {{- end }}
      serviceAccountName: {{ template "serviceAccountName" . }}
      restartPolicy: Always
      volumes:
        - name: rollsite-confs
          configMap:
            name: rollsite-config
---
apiVersion: v1
kind: Service
metadata:
  name: rollsite
  labels:
    fateMoudle: rollsite
{{ include "fate.labels" . | indent 4 }}
spec:
  ports:
    - name: "tcp-rollsite"
      port: 9370
      targetPort: 9370
      {{- if eq .Values.modules.rollsite.type "NodePort" "LoadBalancer" }}
      nodePort: {{ .Values.modules.rollsite.nodePort }}
      {{- end }}
      protocol: TCP
  type: {{ .Values.modules.rollsite.type }}
  {{- if .Values.modules.rollsite.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.modules.rollsite.loadBalancerIP }}"
  {{- end }}
  selector:
    fateMoudle: rollsite
{{ include "fate.matchLabels" . | indent 4 }}
---
{{ end }}
