
image:
  registry: {{ .registry | default "federatedai" }}
  isThridParty: {{ empty .registry | ternary  "false" "true" }}
  tag: 1.4.2-release
  pullPolicy: {{ .pullPolicy | default "IfNotPresent" }}

partyId: {{ .partyId }}
partyName: {{ .name }}

host:
  fateboard: {{ .partyId }}.fateboard.kubefate.net
  client: {{ .partyId }}.notebook.kubefate.net

nodePort: {{ with .rollsite }}{{ .nodePort }}{{ end }}

istio:
  enabled: {{ with .istio }}{{ .enabled | default false }}{{ end }}

exchange:
{{- with .rollsite }}
{{- with .exchange }}
  partyIp: {{ .ip }}
  partyPort: {{ .port }}
{{- end }}
{{- end }}

partyList:
{{- with .rollsite }}
{{- range .partyList }}
  - partyId: {{ .partyId }}
    partyIp: {{ .partyIp }}
    partyPort: {{ .partyPort }}
{{- end }}
{{- end }}

persistence:
  enabled: {{ .persistence | default "false" }}

modules:
  rollsite: 
    include: {{ has "rollsite" .modules }}
    ip: rollsite
    type: {{ .rollsite.type | default "ClusterIP" }}
    {{- with .rollsite }}
    {{- with .nodeSelector }}
    nodeSelector: 
    {{- range $k, $v := . }}
      {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
  python: 
    include: {{ has "python" .modules }}
    fateboardIp: fateboard
    fateboardType: ClusterIP
    fateflowIp: fateflow
    {{- with .python }}
    fateflowType: {{ .fateflowType | default "ClusterIP" }}
    fateflowNodePort: {{ .fateflowNodePort }}
    {{- with .nodeSelector }}
    nodeSelector: 
    {{- range $k, $v := . }}
      {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
  clustermanager: 
    include: {{ has "clustermanager" .modules }}
    ip: clustermanager
    type: ClusterIP
    {{- with .clustermanager }}
    {{- with .nodeSelector }}
    nodeSelector: 
    {{- range $k, $v := . }}
      {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
  nodemanager:  
    include: {{ has "nodemanager" .modules }}
    list:
    {{- with .nodemanager }}
    {{- $nodemanager := . }}
    {{- range .count | int | until }}
    - name: nodemanager-{{ . }}
      nodeSelector: {}
      sessionProcessorsPerNode: {{ $nodemanager.sessionProcessorsPerNode }}
      subPath: "nodemanager-{{ . }}"
      existingClaim: ""
      storageClass: "{{ $nodemanager.storageClass }}"
      accessMode: {{ $nodemanager.accessMode }}
      size: {{ $nodemanager.size }}
    {{- end }}

    {{- range  $nodemanager.list }}
    - name: {{ .name }}
      {{- with .nodeSelector }}
      nodeSelector: 
      {{- range $k, $v := . }}
        {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
      sessionProcessorsPerNode: {{ .sessionProcessorsPerNode }}
      subPath: {{ .subPath }}
      existingClaim: {{ .existingClaim }}
      storageClass: {{ .storageClass }}
      accessMode: {{ .accessMode }}
      size: {{ .size }}
    {{- end }}
    {{- end }}
  client: 
    include: {{ has "client" .modules }}
    ip: client
    type: ClusterIP
    {{- with .client }}
    {{- with .nodeSelector }}
    nodeSelector: 
    {{- range $k, $v := . }}
      {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
  mysql: 
    {{- if .mysql }}
    include: {{ has "mysql" .modules }}
    type: ClusterIP
    {{- with .mysql }}
    {{- with .nodeSelector }}
    nodeSelector: 
    {{- range $k, $v := . }}
      {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
    ip: {{ .mysql.ip | default "mysql" }}
    port: {{ .mysql.port | default "3306" }}
    database: {{ .mysql.database | default "eggroll_meta" }}
    user: {{ .mysql.user | default "fate" }}
    password: {{ .mysql.password | default "fate_dev" }}
    subPath: {{ .mysql.subPath }}
    existingClaim: {{ .mysql.existingClaim }}
    storageClass: {{ .mysql.storageClass }}
    accessMode: {{ .mysql.accessMode | default "ReadWriteOnce" }}
    size: {{ .mysql.size | default "1Gi" }}
    {{- else }}
    include: {{ has "mysql" .modules }}
    type: ClusterIP
    nodeSelector: {}
    ip: {{ .externalMysqlIp | default "mysql" }}
    port: {{ .externalMysqlPort | default "3306" }}
    database: {{ .externalMysqlDatabase | default "eggroll_meta" }}
    user: {{ .externalMysqlUser | default "fate" }}
    password: {{ .externalMysqlPassword | default "fate_dev" }}
    subPath: ""
    existingClaim: ""
    storageClass: "mysql"
    accessMode: ReadWriteOnce
    size: 1Gi
    {{- end }}
  serving:
    ip: {{ .servingIp }}
    port: {{ .servingPort }}
    
