apiVersion: batch/v1
kind: Job
metadata:
  name: fate-mysql-upgrade-job-{{ .start }}-to-{{ .target }}
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: fum
      containers:
        - name: fate-mysql-upgrader
          image: federatedai/fate-upgrade-manager:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-c"
            - |
              python shutdown-flow.py {{ .Release.Namespace }}
              {{- with .Values }}
              python upgrade-mysql.py {{ .username }} {{ .password }} {{ .start }} {{ .target }}w
              {{- end }}
      restartPolicy: Never
