apiVersion: batch/v1
kind: Job
{{- with .Values }}
metadata:
  name: fate-mysql-upgrade-job-{{ .start }}-to-{{ .target }}
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: fum
      containers:
        - name: fate-mysql-upgrader
          image: federatedai/fate-upgrade-manager:latest
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/bash"
            - "-c"
            - |
              python shutdown-flow.py {{ .namespace }}
              python upgrade-mysql.py {{ .username }} {{ .password }} {{ .start }} {{ .target }}
      restartPolicy: Never
{{- end }}