apiVersion: v1
kind: ServiceAccount
metadata:
  name: fum
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fum
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fum-role
subjects:
  - kind: ServiceAccount
    name: fum
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fum-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/status
  - statefulsets
  - statefulsets/status
  verbs:
  - update
  - patch
  - list
  - get