apiVersion: v1
kind: ServiceAccount
metadata:
  name: fum
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fum
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fum-role
subjects:
  - kind: ServiceAccount
    name: fum
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fum-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - update
  - patch