# component provider, relative path to get_fate_python_directory
default_component_provider_path: federatedml

# resource
total_cores_overweight_percent: 1  # 1 means no overweight
total_memory_overweight_percent: 1  # 1 means no overweight
task_parallelism: 1
task_cores: 4
task_memory: 0  # mb
max_cores_percent_per_job: 1  # 1 means total

# scheduling
job_timeout: 259200 # s
remote_request_timeout: 30000  # ms
federated_command_trys: 3
end_status_job_scheduling_time_limit: 300000 # ms
end_status_job_scheduling_updates: 1
auto_retries: 0
auto_retry_delay: 1  #seconds
# It can also be specified in the job configuration using the federated_status_collect_type parameter
federated_status_collect_type: PUSH

# upload
upload_max_bytes: 4194304000 # bytes

#component output
output_data_summary_count_limit: 100