########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.servingProxy.include }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: serving-proxy-config
  labels:
    fateMoudle: serving-proxy
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote }}
    owner: kubefate
    cluster: fate-serving
data:
  application.properties: |
    # same as partyid
    coordinator={{ .Values.partyId }}
    server.port=8059
    #inference.service.name=serving
    ## actuator
    #management.server.port=10087
    #management.endpoints.web.exposure.include=health,info,metrics
    
    #random, consistent
    #routeType=random
    
    #route.table=/data/projects/fate-serving/serving-proxy/conf/route_table.json
    #auth.file=/data/projects/fate-serving/serving-proxy/conf/auth_config.json
    
    useZkRouter=false
    zk.url=zookeeper://localhost:2181
    
    # zk acl
    #acl.enable=false
    #acl.username=
    #acl.password=
    
    # intra-partyid port
    proxy.grpc.intra.port=8879
    # inter-partyid port
    proxy.grpc.inter.port=8869
    
    #proxy.grpc.inference.timeout=3000
    #proxy.grpc.inference.async.timeout=1000
    #proxy.grpc.unaryCall.timeout=3000
    
    
    
    #proxy.grpc.threadpool.coresize=50
    #proxy.grpc.threadpool.maxsize=100
    #proxy.grpc.threadpool.queuesize=10
    
    #proxy.async.timeout=5000
    #proxy.async.coresize=10
    #proxy.async.maxsize=100

  route_table.json: |
    {
        "route_table": {
          "default": {
            "default": [
                {
                  {{- with .Values.servingProxy.exchange }}
                    "ip": "{{ .partyIp }}",
                    "port": {{ .partyPort }}
                  {{- else }}
                    "ip": "default-serving-proxy",
                    "port": 8869
                  {{- end }}
                }
            ]
          },
            {{- range .Values.servingProxy.partyList }}
            {{ .partyId | quote}}: {
                "default": [
                    {
                        "ip": {{ .partyIp | quote }},
                        "port": {{ .partyPort | quote }}
                    }
                ]
            },
            {{- end }}
            {{ .Values.partyId | quote }}: {
                "default": [
                    {
                        "ip": {{ .Values.servingProxy.ip | quote }},
                        "port": 8059
                    }
                ],
                "serving": [
                    {
                        "ip": {{ .Values.servingServer.ip | quote }},
                        "port": 8000
                    }
                ]
            }
        },
        "permission": {
          "default_allow": true
        }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-proxy
  labels:
    fateMoudle: serving-proxy
    name: {{ .Values.partyName  | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate-serving
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      fateMoudle: serving-proxy
      name: {{ .Values.partyName  | quote }}
      partyId: {{ .Values.partyId | quote  }}
  template:
    metadata:
      labels:
        fateMoudle: serving-proxy
        name: {{ .Values.partyName | quote  }}
        partyId: {{ .Values.partyId | quote  }}
        owner: kubefate
        cluster: fate-serving
    spec:
      containers:
        - image: {{ .Values.image.registry }}/serving-proxy:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: serving-proxy
          ports:
            - containerPort: 8059
            - containerPort: 8869
          volumeMounts:
            - mountPath: /data/projects/fate/serving-proxy/conf/application.properties
              name: serving-proxy-confs
              subPath: application.properties
            - mountPath: /data/projects/fate/serving-proxy/conf/route_table.json
              name: serving-proxy-confs
              subPath: route_table.json
      {{- with .Values.servingProxy.nodeSelector }}
      nodeSelector:
      {{- range $k,$v := . }}
        {{ $k }}: {{ $v }}
      {{- end }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: serving-proxy-confs
          configMap:
            name: serving-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    fateMoudle: serving-proxy
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote }}
    owner: kubefate
    cluster: fate-serving
  name: serving-proxy
spec:
  ports:
    - name: "8059"
      port: 8059
      targetPort: 8059
      protocol: TCP
    - name: "8869"
      port: 8869
      targetPort: 8869
      nodePort: {{ .Values.servingProxy.nodePort }}
      protocol: TCP
    - name: "8879"
      port: 8879
      targetPort: 8879
      protocol: TCP
  type: {{ .Values.servingProxy.type }}
  selector:
    fateMoudle: serving-proxy
    name: {{ .Values.partyName | quote }}
    partyId: {{ .Values.partyId | quote  }}
---
{{ end }}