# Copyright 2019-2020 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Values.servingProxy.include }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: serving-proxy
  labels:
    fateMoudle: serving-proxy
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  rules:
  - host: {{ .Values.servingProxy.ingerssHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: serving-proxy
          servicePort: 8059
---
{{ end }}

{{ if .Values.servingAdmin.include }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: serving-admin
  labels:
    fateMoudle: serving-admin
    name: {{ .Values.partyName | quote  }}
    partyId: {{ .Values.partyId | quote  }}
    owner: kubefate
    cluster: fate
spec:
  rules:
    - host: {{ .Values.servingAdmin.ingerssHost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: serving-admin
              servicePort: 8350
---
{{ end }}