{{- if .Values.podSecurityPolicy.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    fateModule: serviceAccount
{{ include "fate.labels" . | indent 4 }}
  name: {{ .Values.partyName }}
{{- end -}}
