########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ .Values.partyId }}: serving-server
  name: serving-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{ .Values.partyId }}: serving-server
  template:
    metadata:
      labels:
        {{ .Values.partyId }}: serving-server
    spec:
      containers:
        - image: {{ .Values.image.registry }}/serving-server:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: serving-server
          ports:
            - containerPort: 8001
          volumeMounts:
            - mountPath: /data/projects/fate/serving-server/conf/serving-server.properties
              name: serving-server-confs
              subPath: serving-server.properties
      {{ if .Values.nodeSelector.servingServer.value}}
      nodeSelector:
        {{ .Values.nodeSelector.servingServer.nodeLabel }}: {{ .Values.nodeSelector.servingServer.value }}
      {{ end }}
      restartPolicy: Always
      volumes:
        - name: serving-server-confs
          configMap:
            name: serving-server-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.partyId }}: serving-server
  name: serving-server
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
  selector:
    {{ .Values.partyId }}: serving-server
