apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fateboard-ingress
spec:
  rules:
  - host: {{ .Values.host.fateboard }}
    http:
      paths:
      - path: /
        backend:
          serviceName: fateboard
          servicePort: 8080