########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.python.include }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fateboard-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.host.fateboard }}
    http:
      paths:
      - path: /
        backend:
          serviceName: fateboard
          servicePort: 8080
---
{{ end }}