########################################################
# Copyright 2019-2020 program was created VMware, Inc. #
# SPDX-License-Identifier: Apache-2.0                  #
########################################################

{{ if .Values.modules.proxy.include}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ .Values.partyId }}: proxy
  name: proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{ .Values.partyId }}: proxy
  template:
    metadata:
      labels:
        {{ .Values.partyId }}: proxy
    spec:
      containers:
        - image: {{ .Values.image.registry }}/proxy:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: proxy
          ports:
            - containerPort: 9370
          volumeMounts:
            - mountPath: /data/projects/fate/proxy/conf/proxy.properties
              name: proxy-confs
              subPath: proxy.properties
            - mountPath: /data/projects/fate/proxy/conf/route_table.json
              name: proxy-confs
              subPath: route_table.json
            - mountPath: /data/projects/fate/proxy/conf/applicationContext-proxy.xml
              name: other-confs
              subPath: applicationContext-proxy.xml
            - mountPath: /data/projects/fate/proxy/conf/log4j2.properties
              name: other-confs
              subPath: log4j2.properties
      {{ if .Values.nodeSelector.proxy.value}}
      nodeSelector:
        {{ .Values.nodeSelector.proxy.nodeLabel }}: {{ .Values.nodeSelector.proxy.value }}
      {{ end }}
      restartPolicy: Always
      volumes:
        - name: proxy-confs
          configMap:
            name: proxy-config
        - name: other-confs
          configMap:
            name: proxy-config-other
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.partyId }}: proxy
  name: proxy
spec:
  ports:
    - name: "9370"
      port: 9370
      nodePort: {{ .Values.nodePort }}
      targetPort: 9370
      protocol: TCP
  type: {{ .Values.modules.proxy.type }}
  selector:
    {{ .Values.partyId }}: proxy
---
{{ end }}