# Copyright 2019-2022 VMware, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.modules.python.include }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: python
  labels:
    fateMoudle: python
{{ include "fate.labels" . | indent 4 }}
spec:
  serviceName: fateflow
  replicas: {{ .Values.modules.python.replicas }}
  selector:
    matchLabels:
      fateMoudle: python
{{ include "fate.matchLabels" . | indent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        {{- end }}
      labels:
        fateMoudle: python
{{ include "fate.labels" . | indent 8 }}
    spec:
      {{- if .Values.istio.enabled }}
      {{- else }}
      initContainers:
      - image: {{ .Values.image.registry }}{{ .Values.modules.mysql.image }}:{{ .Values.modules.mysql.imageTag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: ping-mysql
        env:
        - name: MYSQL_DATABASE
          value: "{{ .Values.externalMysqlDatabase | default .Values.modules.mysql.database | default "eggroll_meta" }}"
        - name: MYSQL_USER
          value: "{{ .Values.externalMysqlUser | default .Values.modules.mysql.user | default "fate" }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.externalMysqlPassword | default .Values.modules.mysql.password | default "fate_dev" }}"
        - name: MYSQL_HOST
          value: "{{ .Values.externalMysqlIp | default .Values.modules.mysql.ip | default "mysql" }}"
        - name: MYSQL_PORT
          value: "{{ .Values.externalMysqlPort | default .Values.modules.mysql.port | default "3306" | }}"
        command:
        - /bin/bash
        - -c
        - |
          set -x
          function checkMySQL(){
            checkMySQLCount=0
            while true ; do
              checkMySQLCount=$[checkMySQLCount+1]
              echo "Waiting for mysql started. check count: $checkMySQLCount"
              sleep 2

              state=`mysqladmin ping -h ${MYSQL_HOST} --port=${MYSQL_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD}| awk '{print $3}'`
              if [ "$state" == "alive" ]; then
                echo "mysql server has been already started."
              break
              fi
           done
          }
          echo "Waiting for mysql started..."
          checkMySQL
      {{- end }}
      containers:
        - name: fateflow
          image: {{ .Values.image.registry }}{{ .Values.modules.python.image }}{{ include "images.fateflow.suffix" . }}:{{ .Values.modules.python.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.modules.python.resources}}
          resources:
          {{- range $key, $val := .Values.modules.python.resources }}
            {{ $key }}:
{{ toYaml $val | indent 14 }}
          {{- end }}
          {{- end }}
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- if .Values.modules.python.logLevel }}
          - name: FATE_LOG_LEVEL
            value: {{ .Values.modules.python.logLevel }}
          {{- end }}
          - name: FATE_PROJECT_BASE
            value: "/data/projects/fate"
          - name: HUGGINGFACE_HUB_CACHE
            value: "/data/projects/fate/llm"
          {{- if eq .Values.computing "Spark" }}
          - name: FATE_FLOW_UPLOAD_MAX_NUM
            value: "1000000"
          - name: FATE_FLOW_UPLOAD_MAX_BYTES
            value: "104868093952"
          {{- end }}
          ports:
            - name: grpc-port
              containerPort: 9360
            - name: http-port
              containerPort: 9380
          command:
            - /bin/bash
            - -c
            - |
                set -x
                mkdir -p /data/projects/fate/conf/
                cp /data/projects/fate/conf-tmp/service_conf.yaml /data/projects/fate/fate_flow/conf/service_conf.yaml
                # fix fateflow conf must use IP
                sed -i "s/host: fateflow_ip/host: ${POD_IP}/g" /data/projects/fate/fate_flow/conf/service_conf.yaml
                
                cp /data/projects/spark-3.1.3-bin-hadoop3.2/conf/spark-defaults-template.conf /data/projects/spark-3.1.3-bin-hadoop3.2/conf/spark-defaults.conf
                sed -i "s/fateflow/${POD_IP}/g" /data/projects/spark-3.1.3-bin-hadoop3.2/conf/spark-defaults.conf
                
                pip install cryptography && sleep 5 && python fate_flow/python/fate_flow/fate_flow_server.py
          livenessProbe:
            tcpSocket:
              port: 9380
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9380
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 9380
            failureThreshold: 12
            periodSeconds: 10
          volumeMounts:
            {{- if eq .Values.computing "Eggroll" }}
            - mountPath: /data/projects/fate/eggroll/conf/eggroll.properties
              name: eggroll-confs
              subPath: eggroll.properties
            {{- end }}
            - name: python-data
              mountPath: /data/projects/fate/fate_flow/logs
              subPath: logs
            - mountPath: /data/projects/fate/conf-tmp/
              name: python-confs
            - mountPath: /data/projects/spark-3.1.3-bin-hadoop3.2/conf/spark-defaults-template.conf
              name: python-confs
              subPath: spark-defaults.conf
            {{- if eq .Values.federation "RabbitMQ" }}
            - mountPath: /data/projects/fate/conf/rabbitmq_route_table
              name: rabbitmq-route-table
            {{- end }}
            {{- if eq .Values.federation "Pulsar" }}
            - mountPath: /data/projects/fate/conf/pulsar_route_table
              name: pulsar-route-table
            {{- end }}
            - mountPath: /data/projects/fate/fate_flow/jobs
              name: python-data
              subPath: jobs
            - mountPath: /data/projects/fate/fate_flow/model_local_cache
              name: python-data
              subPath: model-local-cache
            - mountPath: /data/projects/fate/llm
              name: python-data
              subPath: llm
      {{- with .Values.modules.python.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.python.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.modules.python.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
      {{- end }}
    {{- if .Values.modules.python.serviceAccountName }}
      serviceAccountName: {{ .Values.modules.python.serviceAccountName }}
    {{- else }}
      serviceAccountName: {{ template "serviceAccountName" . }}
    {{- end }}
      restartPolicy: Always
      volumes:
        {{- if eq .Values.computing "Eggroll" }}
        - name: eggroll-confs
          configMap:
            name: eggroll-config
        {{- end }}
        - name: python-confs
          configMap:
            name: python-config
        {{- if eq .Values.federation "RabbitMQ" }}
        - name: rabbitmq-route-table
          configMap:
            name: rabbitmq-route-table
        {{- end }}
        {{- if eq .Values.federation "Pulsar" }}
        - name: pulsar-route-table
          configMap:
            name: pulsar-route-table
        {{- end }}
        {{- if not .Values.persistence.enabled }}
        - name: python-data
          emptyDir: {}
        {{- else if and .Values.persistence.enabled (.Values.modules.python.existingClaim) }}
        - name: python-data
          persistentVolumeClaim:
            claimName: {{ .Values.modules.python.existingClaim | default  "python-data" }}
        {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: python-data
        labels:
          fateMoudle: python
{{ include "fate.labels" . | indent 10 }}
      spec:
        accessModes: [{{ .Values.modules.python.accessMode | quote }}]
        storageClassName: {{ .Values.modules.python.storageClass }}
        resources:
          requests:
            storage: {{ .Values.modules.python.size }}
        {{- end }}
{{- end }}
