name: A workflow for docker deploy ci
on: pull_request
jobs:
  build:
    name: Docker deploy action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: generate config
      if: success()
      run: |
        bash ci/docker-deploy/generate_config.sh

    - name: docker deploy
      if: success()
      run: |
        bash ci/docker-deploy/docker_deploy.sh

    - name: toy example test
      if: success()
      run: |
        bash ci/docker-deploy/test_cluster.sh
