name: Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - jenkins-integration

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # no test is required
  push:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Prepare the TAG
        id: prepare-the-tag
        run: |
          # strip git ref prefix from version
          TAG=""
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ $VERSION = "master" ]; then
            TAG="latest"
          else
            TAG="$VERSION"
          fi
          echo "::set-output name=tag::$TAG"
      - name: Build image
        run: |
          export VERSION=${{steps.prepare-the-tag.outputs.tag}} 
          cd k8s-deploy
          make docker-build

      - name: Log into DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          export VERSION=${{steps.prepare-the-tag.outputs.tag}} 
          cd k8s-deploy
          make docker-push
